### ISSUE TITLE
soiboi2.0: todo feature list

### ISSUE THREAD

**Issue by cr1tbit** [hspsh/short-of-inventory#3]
- [ ] Add column "url" to DB - this will store a single link per label
- [ ] Add second "print" button, for labella, with new sticker format
- [ ] Use column "raw" to format normal entries
- [ ] add SSO login
- [ ] add edit for logged-in users
- [ ] modify web template for new features
